package square;

public enum EffectType {
	CURSEPLAYEREFFECT, DECREMENTDISKRANGEEFFECT, DISKEFFECT, DROPFLAGEFFECT, EXPLOSIONEFFECT, 
	FORCEFIELDEFFECT, IDENTITYDISKDESTROYEFFECT, LOSEACTIONEFFECTONPLAYER, LOSETURNEFFECTONPLAYER,
	PLAYEREFFECT, STARTINGPOSITIONEFFECT, TELEPORTIDENTITYDISKEFFECT, 
	TELEPORTPLAYEREFFECT;
}
