package square;

public enum OnSquareType {
	IDENTITYDISK, CHARGEDIDENTITYDISK, PLAYER, WALL, FORCEFIELD, FORCEFIELDGENERATOR,
	POWERFAILUREPRIM, POWERFAILURESEC, POWERFAILURETERT, LIGHTGRENADE, FLAG, STARTINGPOSITION,
	TELEPORTER, LIGHTTRAIL;
}
